export const PRESET_ID = "info.n@cumak.net";
export const GUEST_ID = "info.pcpguest@cumak.net";

export const ADD_ONPU_TOONKIGOU = [
  { onpuName: "ド", dataNum: 1 },
  { onpuName: "シ", dataNum: 2 },
  { onpuName: "ラ", dataNum: 3 },
  { onpuName: "ソ", dataNum: 4 },
  { onpuName: "ファ", dataNum: 5 },
  { onpuName: "ミ", dataNum: 6 },
  { onpuName: "レ", dataNum: 7 },
  { onpuName: "ド", dataNum: 8 },
  { onpuName: "シ", dataNum: 9 },
  { onpuName: "ラ", dataNum: 10 },
  { onpuName: "ソ", dataNum: 11 },
  { onpuName: "ファ", dataNum: 12 },
  { onpuName: "ミ", dataNum: 13 },
  { onpuName: "レ", dataNum: 14 },
  { onpuName: "ド", dataNum: 15 },
  { onpuName: "シ", dataNum: 16 },
  { onpuName: "ラ", dataNum: 17 },
  { onpuName: "ソ", dataNum: 18 },
];
export const ADD_ONPU_HEONKIGOU = [
  { onpuName: "レ", dataNum: 19 },
  { onpuName: "ド", dataNum: 20 },
  { onpuName: "シ", dataNum: 21 },
  { onpuName: "ラ", dataNum: 22 },
  { onpuName: "ソ", dataNum: 23 },
  { onpuName: "ファ", dataNum: 24 },
  { onpuName: "ミ", dataNum: 25 },
  { onpuName: "レ", dataNum: 26 },
  { onpuName: "ド", dataNum: 27 },
  { onpuName: "シ", dataNum: 28 },
  { onpuName: "ラ", dataNum: 29 },
  { onpuName: "ソ", dataNum: 30 },
  { onpuName: "ファ", dataNum: 31 },
  { onpuName: "ミ", dataNum: 32 },
  { onpuName: "レ", dataNum: 33 },
];

export const TONE_DATA = {
  1: ["C", 6, "R"],
  2: ["B", 5, "R"],
  3: ["A", 5, "R"],
  4: ["G", 5, "R"],
  5: ["F", 5, "R"],
  6: ["E", 5, "R"],
  7: ["D", 5, "R"],
  8: ["C", 5, "R"],
  9: ["B", 4, "R"],
  10: ["A", 4, "R"],
  11: ["G", 4, "R"],
  12: ["F", 4, "R"],
  13: ["E", 4, "R"],
  14: ["D", 4, "R"],
  15: ["C", 4, "R"],
  16: ["B", 3, "R"],
  17: ["A", 3, "R"],
  18: ["G", 3, "R"],

  19: ["D", 4, "L"],
  20: ["C", 4, "L"],
  21: ["B", 4, "L"],
  22: ["A", 3, "L"],
  23: ["G", 3, "L"],
  24: ["F", 3, "L"],
  25: ["E", 3, "L"],
  26: ["D", 3, "L"],
  27: ["C", 3, "L"],
  28: ["B", 2, "L"],
  29: ["A", 2, "L"],
  30: ["G", 2, "L"],
  31: ["F", 2, "L"],
  32: ["E", 2, "L"],
  33: ["D", 2, "L"],
};
