export const ADD_ONPU_TOONKIGOU = [
  { onpuName: "ド", dataNum: 1 },
  { onpuName: "シ", dataNum: 2 },
  { onpuName: "ラ", dataNum: 3 },
  { onpuName: "ソ", dataNum: 4 },
  { onpuName: "ファ", dataNum: 5 },
  { onpuName: "ミ", dataNum: 6 },
  { onpuName: "レ", dataNum: 7 },
  { onpuName: "ド", dataNum: 8 },
  { onpuName: "シ", dataNum: 9 },
  { onpuName: "ラ", dataNum: 10 },
  { onpuName: "ソ", dataNum: 11 },
  { onpuName: "ファ", dataNum: 12 },
  { onpuName: "ミ", dataNum: 13 },
  { onpuName: "レ", dataNum: 14 },
  { onpuName: "ド", dataNum: 15 },
  { onpuName: "シ", dataNum: 16 },
  { onpuName: "ラ", dataNum: 17 },
  { onpuName: "ソ", dataNum: 18 },
];
export const ADD_ONPU_HEONKIGOU = [
  { onpuName: "レ", dataNum: 19 },
  { onpuName: "ド", dataNum: 20 },
  { onpuName: "シ", dataNum: 21 },
  { onpuName: "ラ", dataNum: 22 },
  { onpuName: "ソ", dataNum: 23 },
  { onpuName: "ファ", dataNum: 24 },
  { onpuName: "ミ", dataNum: 25 },
  { onpuName: "レ", dataNum: 26 },
  { onpuName: "ド", dataNum: 27 },
  { onpuName: "シ", dataNum: 28 },
  { onpuName: "ラ", dataNum: 29 },
  { onpuName: "ソ", dataNum: 30 },
  { onpuName: "ファ", dataNum: 31 },
  { onpuName: "ミ", dataNum: 32 },
];
